### ISSUE TITLE
Support older versions of .NET Framework

### ISSUE THREAD

**Issue by jnm2** [tunnelvisionlabs/ReferenceAssemblyAnnotator#26]
My company has some projects that extend third-party .NET Framework 3.5 software. We don't have control over the entry point, so these projects are largely stuck with the world as it was eleven years ago.

There doesn't seem to be any reason not to allow this package to annotate as far back as `net35`, does there? From the perspective of what I understand this package to do, `net35` *is* `net472`, only with fewer APIs.

I extracted https://globalcdn.nuget.org/packages/tunnelvisionlabs.referenceassemblyannotator.1.0.0-alpha.53.nupkg to `%userprofile%/.nuget/packages/tunnelvisionlabs.referenceassemblyannotator.1.0.0/alpha.53`, deleted the signature, and changed the nuspec dependency to `.NETFramework,3.5`. The package then installs successfully.

Would you accept a PR to permit this scenario?

**Comment by sharwell** [comment]
The tool was intended to support net20 and newer.

**Comment by sharwell** [comment]
It looks like #27 did fix this after all 😄
