### ISSUE TITLE
NoWarn doesn't suppress RA1000

### ISSUE THREAD

**Issue by jnm2** [tunnelvisionlabs/ReferenceAssemblyAnnotator#31]
A net35 project that uses System.Data will cause a RA1000 warning. Since there's nothing I can do about this—nothing under my control is misconfigured—I tried acknowledging the warning by adding `<NoWarn>RA1000</NoWarn>` to the project.

It had no effect since by default the list is passed to csc which has nothing to do with this, but I'm interested in some way of suppressing it. I know that other SDK targets like NuGet stuff respect NoWarn. Is that what should happen here?

**Comment by sharwell** [comment]
💭 I think `NoWarn` needs to be passed to the build task.
