### ISSUE TITLE
Remove the notnull constraint from IDictionary<TKey, TValue> keys

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/ReferenceAssemblyAnnotator#52]
This will work around dotnet/corefx#42386 for the 3.x releases until the constraint is removed for .NET 5.

**Comment by jnm2** [comment]
The constraint should also be removed from IReadOnlyDictionary and several extension methods. This is the diff to follow: https://github.com/dotnet/runtime/commit/48a78bfa13e9c710851690621fc2c0fe1637802c

The `notnull` constraint was removed from the `TKey` generic parameter of:

- `IDictionary<TKey, TValue>`
- `IReadOnlyDictionary<TKey, TValue>`
- `CollectionExtensions.GetValueOrDefault<TKey, TValue>`
- `CollectionExtensions.Remove<TKey, TValue>`
- `CollectionExtensions.TryAdd<TKey, TValue>`

**Comment by jnm2** [comment]
@sharwell This can be closed now that 5.0.0 annotations are out. We might also want to update the code snippets in the readme to use 5.0.0.

**Comment by jnm2** [comment]
@sharwell Readme update is ready: #88
