### ISSUE TITLE
Include PackageDownload in targets

### ISSUE THREAD

**Issue by jnm2** [tunnelvisionlabs/ReferenceAssemblyAnnotator#70]
I don't like adding the boilerplate PackageDownload line to every csproj. It would be nice to have this in the targets:

```xml
  <ItemGroup Condition="'$(AnnotatedReferenceAssemblyVersion)' != ''">
    <PackageDownload Include="Microsoft.NETCore.App.Ref" Version="[$(AnnotatedReferenceAssemblyVersion)]" />
  </ItemGroup>
```

If control of the package name is desired, we could do this:

```xml
  <PropertyGroup Condition="'$(AnnotatedReferenceAssemblyPackageName)' != ''">
    <AnnotatedReferenceAssemblyPackageName>Microsoft.NETCore.App.Ref</AnnotatedReferenceAssemblyPackageName>
  </PropertyGroup>

  <ItemGroup Condition="'$(AnnotatedReferenceAssemblyVersion)' != ''">
    <PackageDownload Include="$(AnnotatedReferenceAssemblyPackageName)" Version="[$(AnnotatedReferenceAssemblyVersion)]" />
  </ItemGroup>
```

**Comment by sharwell** [comment]
This is likely not possible (it is certainly not possible for `PackageReference`, but I haven't tried with `PackageDownload`). NuGet does not include props/targets from packages when evaluating the dependency graph.

**Comment by jnm2** [comment]
This makes sense. The package targets aren't available until after the restore phase and the PackageDownload item needs to be present before the restore phase.
