### ISSUE TITLE
MemberNotNull and MemberNotNullWhen

### ISSUE THREAD

**Issue by mikernet** [tunnelvisionlabs/ReferenceAssemblyAnnotator#86]
The two attributes named in the title have been added to C# 9. I presume these can be added to the list for use in projects, same as all the others.

**Comment by jnm2** [comment]
Duplicate of https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/issues/84, but I'm not sure why @kevinchalet closed it since https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/pull/85 wasn't merged.

**Comment by sharwell** [comment]
Duplicate of #84
