### ISSUE TITLE
Consider polyfilling System.Type.op_Equality if it doesn't exist so that C# 9 records can be used on net35

### ISSUE THREAD

**Issue by jnm2** [tunnelvisionlabs/ReferenceAssemblyAnnotator#87]
@sharwell This one seems really easy to implement, and using ReferenceAssemblyAnnotator together with a second reference assembly rewriter sounds like pain. Can ReferenceAssemblyAnnotator find it in its heart to broaden its scope and accept a contribution for this?

**Comment by jnm2** [comment]
Not sure what I was thinking; it couldn't work, because the impl would have to exist at runtime.

**Comment by sharwell** [comment]
You could try to get the compiler to fall back to `object.Equals(object, object)`...

**Comment by jnm2** [comment]
@sharwell I would put a lot of money on them turning this down, based on similar issues I've opened having to do with C# 8 features on .NET Framework.

**Comment by jnm2** [comment]
Fred confirmed my expectations at https://discord.com/channels/732297728826277939/732297994699014164/784527963462959104.
